'use client';
const VISITOR_KEY='otr_visitor_id',SESSION_KEY='otr_session',ATTR_KEY='otr_attribution',CLICK_KEY='otr_click_id',SESSION_TTL=30*60*1000;const uid=()=>crypto.randomUUID();
function safeStorage(type:'localStorage'|'sessionStorage'){try{return window[type]}catch{return null}}
function getVisitorId(){const ls=safeStorage('localStorage');let id=ls?.getItem(VISITOR_KEY);if(!id){id=uid();ls?.setItem(VISITOR_KEY,id)}return id}
function getSession(){const ss=safeStorage('sessionStorage');const now=Date.now();let session:{id:string;lastSeen:number}|null=null;try{session=JSON.parse(ss?.getItem(SESSION_KEY)||'null')}catch{}if(!session||now-session.lastSeen>SESSION_TTL)session={id:uid(),lastSeen:now};session.lastSeen=now;ss?.setItem(SESSION_KEY,JSON.stringify(session));return session.id}
function collectAttribution(){const params=new URLSearchParams(location.search);const keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term','campaign_id','adset_id','ad_id','fbclid','gclid','ttclid'];const fresh:Record<string,string>={};keys.forEach(k=>{const v=params.get(k);if(v)fresh[k]=v});const ls=safeStorage('localStorage');let previous:Record<string,string>={};try{previous=JSON.parse(ls?.getItem(ATTR_KEY)||'{}')}catch{}const merged=Object.keys(fresh).length?{...previous,...fresh}:previous;if(Object.keys(merged).length)ls?.setItem(ATTR_KEY,JSON.stringify(merged));return merged}
function getClickId(){const ls=safeStorage('localStorage');let click=ls?.getItem(CLICK_KEY);if(!click){click=`clk_${uid()}`;ls?.setItem(CLICK_KEY,click)}return click}
function sanitizeProperties(input:Record<string,unknown>={}){const blocked=/pass(word)?|card|cvv|cpf|cnpj|email|phone|name|address|message|text|value/i;return Object.fromEntries(Object.entries(input).filter(([k])=>!blocked.test(k)).slice(0,40).map(([k,v])=>[k,typeof v==='string'?v.slice(0,300):v]))}
export async function track(eventName:string,properties:Record<string,unknown>={}){const payload={event_name:eventName,event_id:uid(),session_id:getSession(),visitor_id:getVisitorId(),click_id:getClickId(),site_id:document.documentElement.dataset.siteId||'main',offer_id:document.documentElement.dataset.offerId||null,page_url:location.href.slice(0,2000),page_path:location.pathname,page_title:document.title,referrer:document.referrer||null,timestamp:new Date().toISOString(),attribution:collectAttribution(),properties:sanitizeProperties(properties)};const endpoint=process.env.NEXT_PUBLIC_TRACKER_ENDPOINT||'/api/track';const body=JSON.stringify(payload);if(navigator.sendBeacon){const ok=navigator.sendBeacon(endpoint,new Blob([body],{type:'application/json'}));if(ok)return}await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body,keepalive:true})}
export function autoTrack(){track('page_view');const maxDepths=new Set<number>();const onScroll=()=>{const doc=document.documentElement;const denominator=Math.max(doc.scrollHeight-innerHeight,1);const depth=Math.round((scrollY/denominator)*100);[25,50,75,90].forEach(mark=>{if(depth>=mark&&!maxDepths.has(mark)){maxDepths.add(mark);track('scroll_depth',{percent:mark})}})};addEventListener('scroll',onScroll,{passive:true});const startedAt=Date.now();const interval=setInterval(()=>{if(!document.hidden)track('engaged_time',{seconds:Math.round((Date.now()-startedAt)/1000)})},30000);const clickHandler=(e:MouseEvent)=>{const el=(e.target as HTMLElement)?.closest('a,button,[data-track]') as HTMLElement|null;if(!el)return;const label=el.getAttribute('data-track')||el.getAttribute('aria-label')||el.textContent?.trim().slice(0,80)||el.tagName;const href=el instanceof HTMLAnchorElement?el.href:null;track('click',{label,href_domain:href?new URL(href,location.href).hostname:null});if(el.matches('[data-checkout], a[href*="checkout"], a[href*="pay."]'))track('checkout_click',{label})};document.addEventListener('click',clickHandler,true);const formHandler=(e:Event)=>{const form=e.target as HTMLFormElement;track('form_submit',{form_id:form.id||null,form_name:form.getAttribute('name')||null})};document.addEventListener('submit',formHandler,true);const visibilityHandler=()=>{if(document.hidden)track('page_exit',{seconds:Math.round((Date.now()-startedAt)/1000)})};document.addEventListener('visibilitychange',visibilityHandler);return()=>{clearInterval(interval);removeEventListener('scroll',onScroll);document.removeEventListener('click',clickHandler,true);document.removeEventListener('submit',formHandler,true);document.removeEventListener('visibilitychange',visibilityHandler)}}
